### ISSUE TITLE
Crates.io lists incorrect repository

### ISSUE THREAD

**Issue by Thiez** [kgtkr/iter-merge-sort#1]
The crate you've uploaded to crates.io [here](https://crates.io/crates/iter-merge-sort) lists [your cron fork](https://github.com/kgtkr/cron) as its repository, instead of this repository.

**Comment by kgtkr** [comment]
thanks!

**Comment by kgtkr** [comment]
ccbeb9af86fee93fb24a37bba4daafa099aeb5e2
